"""HTTP client helpers for interacting with the Strava API."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any
from urllib.parse import urlencode

import httpx

from backend.app.config import AppSettings


class StravaAPIError(RuntimeError):
    """Represent a recoverable Strava API failure with HTTP details.

    Parameters:
        message: Human-readable error context.
        status_code: HTTP status code returned by Strava.

    Returns:
        StravaAPIError: Exception instance.

    Raises:
        None.

    Example:
        >>> err = StravaAPIError("failed", 400)
        >>> err.status_code
        400
    """

    def __init__(self, message: str, status_code: int) -> None:
        """Initialize the StravaAPIError payload.

        Parameters:
            message: Human-readable error string.
            status_code: HTTP response status code.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> StravaAPIError("x", 500).status_code
            500
        """

        super().__init__(message)
        self.status_code = status_code


@dataclass(slots=True)
class StravaTokenResponse:
    """Structured token response from OAuth exchange and refresh operations.

    Parameters:
        athlete_id: Numeric Strava athlete identifier.
        access_token: OAuth access token.
        refresh_token: OAuth refresh token.
        expires_at: UTC datetime when access token expires.
        scope: OAuth scope string returned by Strava.
        token_type: Token type string, usually `Bearer`.

    Returns:
        StravaTokenResponse: Parsed token payload.

    Raises:
        None.

    Example:
        >>> payload = StravaTokenResponse(
        ...     1, "a", "r", datetime.now(UTC), "activity:read", "Bearer"
        ... )
        >>> payload.athlete_id
        1
    """

    athlete_id: int
    access_token: str
    refresh_token: str
    expires_at: datetime
    scope: str | None
    token_type: str | None


class StravaClient:
    """Provide token and activity operations for the Strava REST API.

    Parameters:
        settings: App settings containing Strava endpoints and credentials.
        http_client: Optional preconfigured client for testing.

    Returns:
        StravaClient: Client wrapper around Strava API calls.

    Raises:
        None.

    Example:
        >>> # Typical runtime usage
        >>> # client = StravaClient(settings)
        >>> # connect_url = client.build_connect_url("state-value")
    """

    def __init__(self, settings: AppSettings, http_client: httpx.Client | None = None) -> None:
        """Initialize the Strava API client wrapper.

        Parameters:
            settings: Application settings object.
            http_client: Optional injected HTTP client.

        Returns:
            None.

        Raises:
            None.

        Example:
            >>> # client = StravaClient(settings)
            >>> # isinstance(client, StravaClient)
            >>> # True
        """

        self._settings = settings
        self._http_client = http_client

    def build_connect_url(self, state: str) -> str:
        """Build the Strava OAuth consent URL.

        Parameters:
            state: CSRF-mitigation state token generated by the caller.

        Returns:
            str: Fully formatted authorization URL.

        Raises:
            None.

        Example:
            >>> # client.build_connect_url("abc")
            >>> # 'https://www.strava.com/oauth/authorize?...'
        """

        params = {
            "client_id": self._settings.strava_client_id,
            "response_type": "code",
            "redirect_uri": self._settings.strava_redirect_uri,
            "approval_prompt": "auto",
            "scope": self._settings.strava_scopes,
            "state": state,
        }
        return f"{self._settings.strava_auth_base_url}?{urlencode(params)}"

    def exchange_code_for_token(self, code: str) -> StravaTokenResponse:
        """Exchange an OAuth authorization code for token credentials.

        Parameters:
            code: OAuth authorization code received from Strava callback.

        Returns:
            StravaTokenResponse: Parsed token payload.

        Raises:
            StravaAPIError: Raised when Strava rejects the token exchange request.

        Example:
            >>> # token = client.exchange_code_for_token("code")
        """

        payload = {
            "client_id": self._settings.strava_client_id,
            "client_secret": self._settings.strava_client_secret,
            "code": code,
            "grant_type": "authorization_code",
        }
        return self._parse_token_response(self._post_for_token(payload))

    def refresh_access_token(self, refresh_token: str) -> StravaTokenResponse:
        """Refresh an expired access token using the stored refresh token.

        Parameters:
            refresh_token: Current refresh token for the connected athlete.

        Returns:
            StravaTokenResponse: Parsed fresh token payload.

        Raises:
            StravaAPIError: Raised when refresh fails.

        Example:
            >>> # token = client.refresh_access_token("refresh-token")
        """

        payload = {
            "client_id": self._settings.strava_client_id,
            "client_secret": self._settings.strava_client_secret,
            "refresh_token": refresh_token,
            "grant_type": "refresh_token",
        }
        return self._parse_token_response(self._post_for_token(payload))

    def get_recent_activities(
        self, access_token: str, window_start: datetime, window_end: datetime
    ) -> list[dict[str, Any]]:
        """Fetch all activities in the requested sync window.

        Parameters:
            access_token: Active OAuth access token.
            window_start: Inclusive UTC window start.
            window_end: Inclusive UTC window end.

        Returns:
            list[dict[str, Any]]: Combined activity payloads across pages.

        Raises:
            StravaAPIError: Raised when API requests fail.

        Example:
            >>> # activities = client.get_recent_activities(token, start, end)
        """

        activities: list[dict[str, Any]] = []
        page = 1

        with self._get_http_client() as client:
            while True:
                response = client.get(
                    f"{self._settings.strava_api_base_url}/athlete/activities",
                    params={
                        "after": int(window_start.timestamp()),
                        "before": int(window_end.timestamp()),
                        "page": page,
                        "per_page": self._settings.strava_activity_page_size,
                    },
                    headers={"Authorization": f"Bearer {access_token}"},
                    timeout=30,
                )

                if response.status_code != 200:
                    raise StravaAPIError(
                        f"Failed to fetch activities: {response.text}", response.status_code
                    )

                page_payload = response.json()
                if not page_payload:
                    break

                activities.extend(page_payload)

                # A short page means Strava has no more results to return.
                if len(page_payload) < self._settings.strava_activity_page_size:
                    break

                page += 1

        return activities

    def _post_for_token(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Send a token request to Strava and return parsed JSON.

        Parameters:
            payload: Form fields passed to the token endpoint.

        Returns:
            dict[str, Any]: Parsed JSON response body.

        Raises:
            StravaAPIError: Raised for non-200 responses.

        Example:
            >>> # body = client._post_for_token({...})
        """

        with self._get_http_client() as client:
            response = client.post(self._settings.strava_token_url, data=payload, timeout=30)

        if response.status_code != 200:
            raise StravaAPIError(f"Token request failed: {response.text}", response.status_code)

        return response.json()

    def _parse_token_response(self, payload: dict[str, Any]) -> StravaTokenResponse:
        """Convert raw token payload into a typed dataclass.

        Parameters:
            payload: Raw JSON payload returned by Strava token endpoints.

        Returns:
            StravaTokenResponse: Parsed token response.

        Raises:
            KeyError: Raised if expected fields are missing from payload.

        Example:
            >>> # parsed = client._parse_token_response(raw_payload)
        """

        return StravaTokenResponse(
            athlete_id=int(payload["athlete"]["id"]),
            access_token=payload["access_token"],
            refresh_token=payload["refresh_token"],
            expires_at=datetime.fromtimestamp(int(payload["expires_at"]), tz=UTC),
            scope=payload.get("scope"),
            token_type=payload.get("token_type"),
        )

    def _get_http_client(self) -> httpx.Client:
        """Return an HTTP client, using an injected test client when provided.

        Parameters:
            None.

        Returns:
            httpx.Client: HTTP client instance.

        Raises:
            None.

        Example:
            >>> # with client._get_http_client() as http_client:
            >>> #     ...
        """

        if self._http_client is not None:
            return self._http_client

        return httpx.Client()
